### PR TITLE
Fix warning not being suppressed

### PR DESCRIPTION
**Pull request by mohd-akram**

### CODE REVIEW

**Comment by mohd-akram** [comment]
Could someone take a look at my PRs?

@emackey

**Comment by emackey** [comment]
Thanks @mohd-akram.

Hi @OmarShehata, what's the CLA policy on this repo, does it need one?  The links are to the old AGI Cesium CLA, but it looks like it redirects to the correct place.

**Review by emackey — APPROVED** [review]

**Comment by OmarShehata** [comment]
Wow, I thought I'd seen all the repos! CLA instructions should be updated like in gltf-pipeline: https://github.com/CesiumGS/gltf-pipeline#contributions. All open source repos under CesiumGS are under that CLA.

I can confirm once received since we don't have concierge on this repo.

**Comment by emackey** [comment]
Yeah, this one doesn't see much action these days.  But with some recent events I'm wondering if a fork of this could be used to convert the glTF schema to AsciiDoctor format, which is similar to Markdown.  I don't really have time to build such a thing of course, just pondering.

**Comment by emackey** [comment]
@mohd-akram Are you able to (electronically) sign the CLA that @OmarShehata links to?

**Comment by mohd-akram** [comment]
@emackey I signed it now.

**Comment by OmarShehata** [comment]
Can confirm we've received your CLA. Thanks!

**Comment by emackey** [comment]
Thanks @mohd-akram and @OmarShehata.

**Pull request merged**
