### PR TITLE
Handle relative references for 3D Tiles schema

### LINKED ISSUE #5: Handle 3D Tiles schema
In order to support the [3d-tiles schema](https://github.com/AnalyticalGraphicsInc/3d-tiles/tree/master/schema) these two changes are needed:
* Handle schema references that create circular dependencies. For example in `tile.schema.json`.
* Support references to internal definitions, like in `batchTable.schema.json`.
`{ "$ref" : "#/definitions/binaryBodyReference" }`

### PR DESCRIPTION
**Pull request by ggetz**
Fixes #5 

Handling relative references in the 3D Tiles schema of the from `#/definitions/refName` or `anotherFile.schema.json#/definitions/refName`.

### CODE REVIEW

**Comment by pjcozzi** [comment]
@emackey want to take a quick look?

**Comment by emackey** [comment]
Thanks @ggetz.  I ran this against the glTF schema, and I see a lot of these kind of diffs:

master:

```
### accessor.sparse.indices.bufferView :white_check_mark: 
```

This branch:

```
### AccessorSparseIndices.bufferView :white_check_mark: 
```

Is this an intentional change?  Is there something we could do to keep the glTF titles working?

**Comment by ggetz** [comment]
> Is this an intentional change? Is there something we could do to keep the glTF titles working?

This made sense for the property names when I ran it against 3D Tiles. I'll make sure we are preserving behavior though.

**Comment by evaneus** [comment]
any chance of merging this? looking to use wetzel and need relative references

**Comment by emackey** [comment]
@ggetz Is there a plan for this?  It seems like a good change, but I had an issue with what it did to all the minor headings in the glTF schema.  Is it still worth pursuing, or did you end up using a fork of wetzel?

**Comment by emackey** [comment]
This branch seems inactive, and has many conflicts with recent additions.  Let me know if this picks up steam again at some point in the future.

**Comment by emackey** [comment]
Also it looks like "relative references" above are JSON pointers.  If that's the case, this feature has now been merged in #35.

**Pull request closed without merging**
